#
# VirtIOGPUInstallerLocale - locale wrapper
# Generated by InstallerScriptGen.
#

import catalog


class VirtIOGPUInstallerLocale:
    strings = {}
    cat = None

    MSG_WELCOME = 1
    MSG_FINISH = 2
    MSG_REBOOT = 3

    def __init__(self, language="", catalogName='VirtIOGPU.catalog', builtinLanguage='english'):
        self.strings[self.MSG_WELCOME] = '\nWelcome to the installation of the VirtIOGPU graphics driver.\n\nvirtiogpu.chip is a Picasso96 (RTG) graphics driver for the VirtIO GPU device provided by the QEMU emulator.  It is intended for AmigaOS 4.1 Final Edition systems running inside QEMU and serves no purpose on real hardware.\n\nThe following changes will be made to your system:\n\n    1.  virtiogpu.chip will be copied to "SYS:Kickstart"\n\n    2.  "SYS:Kickstart/Kicklayout" will be updated to load the driver during startup; the previous configuration will be preserved as "Kicklayout.bak"\n\nA system restart is required to complete the installation.\n\n\nPress "Next" to continue.'
        self.strings[self.MSG_FINISH] = '\nThe installation completed successfully.\n\nvirtiogpu.chip has been copied to "SYS:Kickstart" and "SYS:Kickstart/Kicklayout" has been updated.  The previous configuration was preserved as "Kicklayout.bak".  The driver will be activated by the next system restart.\n\nPlease ensure QEMU is started with a VirtIO GPU display device:\n\n    -device virtio-gpu-pci\n\nor, for Virgl GPU acceleration:\n\n    -device virtio-gpu-gl-pci -display sdl,gl=on\n\nPlease note: when restarting from within QEMU, the virtual machine may power off instead of restarting.  Should this occur, simply start QEMU again.\n\n\nPress "Finish" to exit the installation.'
        self.strings[self.MSG_REBOOT] = 'Restart the system now (required to activate the driver)'

        try:
            self.cat = catalog.OpenCatalog(catalogName, language, builtinLanguage)
        except:
            self.cat = None

    def GetString(self, id):
        if self.cat != None:
            return self.cat.GetString(id, self.strings[id])
        return self.strings[id]
